language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
- python3.5 -m pip install -e .
- python3.5 -m pip install git+https://github.com/lycantropos/VKApp.git#egg=vk_app
# command to run tests
script:
- python3.5 -m manage.py test_dao